### PR TITLE
Improve handling of bools, empty strings and falsy values

### PR DESCRIPTION
**Pull request by litenjacob**
Hey @pugnascotia! I noticed some shortcomings around handling of bools, empty strings and falsy values, and hence created this PR.

Let me know if you want any further tweaks. If not, I would very much appreciate a new release so I can get rid of `patch-package`ing my local usage of your excellent `micro-jq` library 🙏 😅

### CODE REVIEW

**Comment by pugnascotia** [comment]
@litenjacob thank you for the PR! Can you please sign the [Contributor Agreement](https://www.elastic.co/contributor-agreement)?

**Comment by litenjacob** [comment]
I tried doing that yesterday, but maybe I didn't do it right? 😬  Is it supposed to automagically pick that up here? If so, how fast?! Do you know if it works by matching the email of my commits, or how does it work?

**Comment by litenjacob** [comment]
Oh, just now when I posted my message, the check seemed to jump into place 😅 💚

**Review by pugnascotia — APPROVED** [review]
LGTM! 👍

**Comment by pugnascotia** [comment]
Thanks @litenjacob! I'll get a release out.

**Comment by pugnascotia** [comment]
Released in v1.7.0

**Pull request merged**
