### PR TITLE
Add a couple of functions

### PR DESCRIPTION
**Pull request by voxpelli**
The tests are not exhaustive, but thinking I would like to throw it out there before spending too much time on it, to see if there's interest in this or not.

Could be extended with the requests in #1, I myself was mostly interested in the `join("foo")`

### CODE REVIEW

**Comment by voxpelli** [comment]
I'll sign the CLA before merging as well of course

**Review by pugnascotia — APPROVED** [review]
@voxpelli I'm so sorry for not reviewing this earlier, the changes look good to me. Would you mind signing the CLA please?

**Comment by voxpelli** [comment]
@pugnascotia No worries! I have signed the CLA now 👍

**Comment by pugnascotia** [comment]
Many thanks again @voxpelli!

**Comment by pugnascotia** [comment]
Published in 1.8.0 🎉

**Pull request merged**
